package: dsgvo
version: '0.8beta2'
title: 'translate:title'
author: 'Friends Of REDAXO, Pixelfirma, alexplus_de, pixeldaniel'
supportpage: 'https://github.com/FriendsOfREDAXO/dsgvo/'
icon: fa-gavel

requires:
    redaxo: ^5.4.0
    packages:
        cronjob: '^2.0'
        markitup: '^3.0'
        yrewrite: '^2.2'
page:
    title: 'translate:title'
    pjax: false
    icon: rex-icon fa-gavel

pages:
    dsgvo/setup:
        title: 'translate:setup'
        icon: rex-icon fa-gavel
    dsgvo/setup/overview:
        title: 'translate:setup-overview'
        icon: rex-icon rex-icon-info
    dsgvo/setup/modul:
        title: 'translate:setup-modul'
        icon: rex-icon rex-icon-module
    dsgvo/setup/backup:
        title: 'translate:setup-backup'
        icon: rex-icon rex-icon-backup
    dsgvo/setup/phpmailer:
        title: 'translate:setup-phpmailer'
        icon: rex-icon rex-icon-envelope
    dsgvo/setup/contactform:
        title: 'translate:setup-contactform'
        icon: rex-icon rex-icon-envelope
    dsgvo/setup/dementia:
        title: 'translate:setup-dementia'
        icon: rex-icon rex-icon-delete
    dsgvo/setup/external:
        title: 'translate:setup-external'
        icon: rex-icon rex-icon-linkmap
    dsgvo/edit:
        title: 'translate:dsgvo_page_edit'
        icon: rex-icon fa-edit
    dsgvo/consent:
        title: 'translate:consent'
        icon: rex-icon fa-check
    dsgvo/docs:
        title: 'translate:docs'
        icon: rex-icon fa-info-circle
        itemclass: pull-right 
